name: "assign-reviewer"
description: "this action help to assign your coworkers as pull request reviewer if condition's matched."

branding:
  icon: "tag"
  color: "blue"

runs:
  using: "node12"
  main: "index.js"
